### ISSUE TITLE
32bit arm failure

### ISSUE THREAD

**Issue by jackmitch** [tuxable-ltd/meta-scikit-learn#1]
Some function of scikit-learn fail on an arm 32 bit system. To reproduce build a scitkit-learn enabled image for arm, an example conf looks like:

```
Build Configuration:
BB_VERSION           = "1.49.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "arch"
TARGET_SYS           = "arm-oe-linux-gnueabi"
MACHINE              = "qemuarm"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon callconvention-hard"
TARGET_FPU           = "hard"
meta                 = "master:68f20ac5524a5db8a09a90df796b4862cf747d3c"
meta-oe              
meta-python          = "master:759058bfb832161eb0d21f5c51a49c8361e727bc"
meta-scikit-learn    = "<unknown>:<unknown>"
```
local.conf additions
```
MACHINE ?= "qemuarm"

IMAGE_INSTALL_append = "python3-scikit-learn"
EXTRA_IMAGE_FEATURES_append = " ssh-server-dropbear"
```

then

```
bitbake core-image-minimal
```

then

```
runqemu
```

once booted you can SSH into the qemu with

```
ssh root@192.168.7.2
```

then run the pytest for the dbscan_inner

```
pytest /usr/lib/python3.9/site-packages/sklearn/cluster/tests/test_dbscan.py
```

which will output the following error

```
================================================ test session starts =================================================
platform linux -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /usr/lib/python3.9/site-packages/sklearn/cluster
collected 28 items                                                                                                   

../../usr/lib/python3.9/site-packages/sklearn/cluster/tests/test_dbscan.py .FFFFatal Python error: Segmentation fault

Current thread 0xb6f76010 (most recent call first):
  File "/usr/lib/python3.9/site-packages/sklearn/neighbors/_base.py", line 503 in _fit
  File "/usr/lib/python3.9/site-packages/sklearn/neighbors/_unsupervised.py", line 142 in fit
  File "/usr/lib/python3.9/site-packages/sklearn/cluster/tests/test_dbscan.py", line 85 in test_dbscan_sparse_precomputed
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 183 in pytest_pyfunc_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/python.py", line 1641 in runtest
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 162 in pytest_runtest_call
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 126 in runtestprotocol
  File "/usr/lib/python3.9/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/usr/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/usr/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/usr/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/usr/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/usr/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/usr/bin/pytest", line 33 in <module>
```

I have identified this as a 64bit -> 32bit compile issue, probably from using the -native include files when building. The exact error from our proprietary codebase looks like:

```
File "sklearn/cluster/_dbscan_inner.pyx", line 40, in sklearn.cluster._dbscan_inner.dbscan_inner
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long long'
```

Which I think makes it obvious that it's using a `long long` type as an integer pointer which would be valid on an 64bit system, but not on a 32bit system.

**Comment by jackmitch** [comment]
This is an example test file in pure Python which shows the issue:

test.py
```
print(__doc__)

import numpy as np

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler


# #############################################################################
# Generate sample data
centers = [[1, 1], [-1, -1], [1, -1]]
X, labels_true = make_blobs(n_samples=750, centers=centers, cluster_std=0.4,
                            random_state=0)

X = StandardScaler().fit_transform(X)

# #############################################################################
# Compute DBSCAN
db = DBSCAN(eps=0.3, min_samples=10).fit(X)
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_

# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)
n_noise_ = list(labels).count(-1)

print('Estimated number of clusters: %d' % n_clusters_)
print('Estimated number of noise points: %d' % n_noise_)
print("Homogeneity: %0.3f" % metrics.homogeneity_score(labels_true, labels))
print("Completeness: %0.3f" % metrics.completeness_score(labels_true, labels))
print("V-measure: %0.3f" % metrics.v_measure_score(labels_true, labels))
print("Adjusted Rand Index: %0.3f"
      % metrics.adjusted_rand_score(labels_true, labels))
print("Adjusted Mutual Information: %0.3f"
      % metrics.adjusted_mutual_info_score(labels_true, labels))
print("Silhouette Coefficient: %0.3f"
      % metrics.silhouette_score(X, labels))
```

```
root@qemuarm:~# python3 test.py 
None
Traceback (most recent call last):
  File "/home/root/test.py", line 21, in <module>
    db = DBSCAN(eps=0.3, min_samples=10).fit(X)
  File "/usr/lib/python3.9/site-packages/sklearn/cluster/_dbscan.py", line 350, in fit
    dbscan_inner(core_samples, neighborhoods, labels)
  File "sklearn/cluster/_dbscan_inner.pyx", line 40, in sklearn.cluster._dbscan_inner.dbscan_inner
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long long'
```

**Comment by jackmitch** [comment]
Jack Mitchell
@jackmitch
Jan 11 14:27
I've cross-compiled scikit-learn for an armv7h system and I'm receiving the following error when testing, does anyone have any suggestions for where the issue may lie?File "sklearn/cluster/_dbscan_inner.pyx", line 40, in sklearn.cluster._dbscan_inner.dbscan_inner
ValueError: Buffer dtype mismatch, expected 'npy_intp' but got 'long long'It looks like it could be something 32bit vs 64bit related but from what I can see the setup.py build system just imports from numpy which I would expect to handle this all properly
so I'm wondering if this isn't a cross compile issue and is maybe just an assumption made in the code that the argument will be 64bit?
a reply from the scikit gitter:

@jackmitch this looks like a bug indeed. I don't have a quick fix from the tip of my head but could you please open an issue on github to avoid forgetting about it? It's probably a temporary buffer that is assigned with an np.int instead of np.intp in our Cython code or wrapping Python code.
Here is a similar bug we had in the past (a long time ago): scikit-learn/scikit-learn@627c564
Ideally a PR would be appreciated because none of us will be able to reproduce it because we do not have access to such hardware.
Also if you want to submit a PR for our doc that documents how you cross-compile scikit-learn for armv7h, that could be useful knowledge to share. For instance it could be a new section at the end of this page: https://scikit-learn.org/dev/developers/advanced_installation.html

6:30
https://github.com/scikit-learn/scikit-learn/commit/627c564faec36c783788b7488b4cf19a2535916c

**Comment by nandra** [comment]
@jackmitch I'm using this layer on dunfell (have problem with compiling scipy-native) so use meta-scipy layer https://github.com/gpanders/meta-scipy (added native recipe there) and build pass and code runs on 64 bit. I have unfortunately not build for 32 bit though but I saw you're making good progress on scikit-learn github issue. Thanks.

**Comment by jackmitch** [comment]
@nandra I don't see the native recipe in meta-scipy, once this is working I have full intentions of upstreaming the scipy native recipe and depending on the layer. I'm not sure why the -native recipe is failing on older builds so if you have a suggestion I would be happy to integrate it.

**Comment by nandra** [comment]
This one I created by myself (plan to push it to meta-scipy):
```
SUMMARY = "SciPy: Scientific Library for Python"
HOMEPAGE = "https://www.scipy.org"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=eb7262aea2504e4c0dfd16f5079e14dd"

SRC_URI = "https://files.pythonhosted.org/packages/a7/5c/495190b8c7cc71977c3d3fafe788d99d43eeb4740ac56856095df6a23fbd/scipy-1.3.3.tar.gz \
           file://0001-Allow-passing-flags-via-FARCH-for-mach.patch \
           "

SRC_URI[md5sum] = "b265efea6ce2f2c1e580cc66bfb8b117"
SRC_URI[sha256sum] = "64bf4e8ae0db2d42b58477817f648d81e77f0b381d0ea4427385bba3f959380a"

S = "${WORKDIR}/scipy-${PV}"

DEPENDS += "${PYTHON_PN}-numpy-native openblas-native lapack-native ${PYTHON_PN}-pybind11-native"

CLEANBROKEN = "1"

inherit setuptools3 native

export LAPACK = "${STAGING_LIBDIR}"
export BLAS = "${STAGING_LIBDIR}"

export F90 = "${TARGET_PREFIX}gfortran"

# Numpy expects the LDSHARED env variable to point to a single
# executable, but OE sets it to include some flags as well. So we split
# the existing LDSHARED variable into the base executable and flags, and
# prepend the flags into LDFLAGS
LDFLAGS_prepend := "${@" ".join(d.getVar('LDSHARED', True).split()[1:])} "
export LDSHARED := "${@d.getVar('LDSHARED', True).split()[0]}"

# Tell Numpy to look in target sysroot site-packages directory for libraries
LDFLAGS_append = " -L${STAGING_LIBDIR}/${PYTHON_DIR}/site-packages/numpy/core/lib"

```

**Comment by jackmitch** [comment]
Seems to work on my end fine so I've pushed this recipe until it makes it into upstream.

**Comment by jackmitch** [comment]
Also, I've hacked a 32bit to work. I've opened a numpy issue to try and gain some traction over there.

https://github.com/numpy/numpy/issues/18209
